### ISSUE TITLE
bug:应用程序无法正常启动，以下是详细的错误信息，希望能够解决，谢谢

### ISSUE THREAD

**Issue by haoxiang1024** [chinosk6/umamusume-voice-text-extractor#15]
D:\下载\umamusume_voice_text_extractor_executeable>.\umamusume_voice_text_extractor\umamusume_voice_text_extractor.exe
Traceback (most recent call last):
  File "D:\chinosk_source\sdk_v2.6.5\umamusume_project\umamusume voice extractor\gui_main.py", line 3, in <module>
  File "gui\guimain.py", line 445, in ui_run_main
  File "gui\guimain.py", line 442, in show_main_window
  File "gui\guimain.py", line 283, in init_main_window
  File "voiceex\live_music\live_music_ex.py", line 14, in __init__
  File "voiceex\resource.py", line 27, in __init__
  File "voiceex\database.py", line 14, in __init__
sqlite3.OperationalError: unable to open database file
[1320] Failed to execute script 'gui_main' due to unhandled exception!

**Comment by chinosk6** [comment]
已有相同 Issue #6 
进一次游戏即可解决
