### ISSUE TITLE
Running error with Gui

### ISSUE THREAD

**Issue by rice1992** [chinosk6/umamusume-voice-text-extractor#16]
my program does not start, the full code goes as thus

D:\워쉽 보이스팩\umamusume_voice_text_extractor_executeable>.\umamusume_voice_text_extractor\umamusume_voice_text_extractor.exe
Traceback (most recent call last):
  File "D:\chinosk_source\sdk_v2.6.5\umamusume_project\umamusume voice extractor\gui_main.py", line 3, in <module>
  File "gui\guimain.py", line 441, in ui_run_main
  File "gui\guimain.py", line 438, in show_main_window
  File "gui\guimain.py", line 285, in init_main_window
  File "gui\guimain.py", line 134, in build_ve_chara_list
  File "gui\guimain.py", line 144, in add_chara_to_list_widget
  File "voiceex\live_music\live_music_ex.py", line 282, in get_char_icon
  File "voiceex\live_music\live_music_ex.py", line 251, in _get_image
  File "voiceex\database.py", line 18, in bundle_hash_to_path
TypeError: 'NoneType' object is not subscriptable
[6020] Failed to execute script 'gui_main' due to unhandled exception!

D:\워쉽 보이스팩\umamusume_voice_text_extractor_executeable>pause
계속하려면 아무 키나 누르십시오 . . .

**Comment by chinosk6** [comment]
Maybe your game data is not fully downloaded. Please full download first.

**Comment by rice1992** [comment]
I use my pc for playing the game(there is a korean pc cilent) and downloaded the extractor on my pc and ran it while the game is fully updated, maybe I am supposed to unpack this in my phone or in my pc umamusume folder?
please advice me as I do not fully understand about fully downloading the data

**Comment by rice1992** [comment]
Many thanks to you, kind sir

**Comment by chinosk6** [comment]
![image](https://github.com/chinosk6/umamusume-voice-text-extractor/assets/74499927/df79c935-da9d-4427-8262-6e927ce813a1)

**Comment by rice1992** [comment]
[image: image.png]

2024년 1월 14일 (일) 오후 12:00, chinosk ***@***.***>님이 작성:

**Comment by rice1992** [comment]
Maybe I should use the dmm japanese version for extract?
and is the unpack  route correct?
[image: image.png]

2024년 1월 14일 (일) 오후 7:42, 사위주 ***@***.***>님이 작성:

**Comment by chinosk6** [comment]
Yes. It only support DMM Japanese version.

**Comment by rice1992** [comment]
Thank you very much for your patience

2024년 1월 14일 (일) 오후 8:10, chinosk ***@***.***>님이 작성:
