### ISSUE TITLE
Failed to execute script 'gui_main' due to unhandled exception!

### ISSUE THREAD

**Issue by Lynx-jr** [chinosk6/umamusume-voice-text-extractor#6]
以下是整个报错信息：
\umamusume_voice_text_extractor.exe
Traceback (most recent call last):
  File "D:\chinosk_source\sdk_v2.6.5\umamusume_project\umamusume voice extractor\gui_main.py", line 3, in <module>
  File "gui\guimain.py", line 391, in ui_run_main
  File "gui\guimain.py", line 388, in show_main_window
  File "gui\guimain.py", line 274, in init_main_window
  File "voiceex\live_music\live_music_ex.py", line 13, in __init__
  File "voiceex\resource.py", line 24, in __init__
  File "voiceex\database.py", line 14, in __init__
sqlite3.OperationalError: unable to open database file
[23344] Failed to execute script 'gui_main' due to unhandled exception!

python版本3.10，相应安装包均为最新，求问应该如何打开GUI？

**Comment by chinosk6** [comment]
先进一次游戏

**Comment by Lynx-jr** [comment]
猴，我再试试！我人在米国，可能是梯子的问题

**Comment by Lynx-jr** [comment]
解决啦！谢谢大大
